### ISSUE TITLE
GRCh38 centromere and telomere coordinates

### ISSUE THREAD

**Issue by JYLeeBioinfo** [cancerit/ClusterSV#5]
Is it okay to use the telomere and centromere coordinates mentioned in the following link?

https://github.com/cancerit/BRASS/issues/101#issuecomment-654846507

**Comment by keiranmraine** [comment]
Yes, I thought I'd added this to the wiki pages but it seems not.  I'll get that sorted.

**Comment by JYLeeBioinfo** [comment]
Thank you! I'll try that one.
